---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: cluster-monitoring
  labels:
    app: alertmanager
    env: production
    monitoring: cluster
data:
  alertmanager.yml: |-
    global: {}
    receivers:
    - name: pagerduty
      pagerduty_configs:
      - service_key: "KEY_HERE"
        severity: "critical"
        send_resolved: true
    - name: slack
      slack_configs:
      - api_url: "HOOK_HERE"
        channel: "#alerts"
        send_resolved: true
        color: '{{ if eq .Status "firing" }}warning{{ else }}good{{ end }}'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Prometheus Alert'
        text: '{{ template "slack.myorg.text" . }}'
    templates:
    - '/etc/alertmanager/config/template_1.tmpl'
        # text: "{{ range .Alerts }}*Summary:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n*Labels:*{{ range .Labels.SortedPairs }}\n- {{ .Name }}: {{ .Value -}}\n{{ end }}{{ end }}"
    route:
      group_interval: 5m
      group_wait: 10s
      group_by: ['alertname', 'env', 'cluster']
      repeat_interval: 2h

      # default receiver is PagerDuty
      receiver: pagerduty
      routes:
      - receiver: slack
        match:
          severity: warning
      - receiver: pagerduty
        match:
          severity: critical
