---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: cluster-monitoring
  labels:
    app: alertmanager
    monitoring: cluster
    env: production
spec:
  progressDeadlineSeconds: 120
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: alertmanager
      env: production
      monitoring: cluster
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: alertmanager
        env: production
        monitoring: cluster
    spec:
      containers:
      - name: alertmanager-reloader
        image: jimmidyson/configmap-reload:v0.2.2
        args:
        - --volume-dir=/etc/config
        - --webhook-url=http://127.0.0.1:9093/-/reload
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/config
          readOnly: true
      - name: alertmanager
        image: prom/alertmanager:v0.15.3
        imagePullPolicy: IfNotPresent
        args:
        - --config.file=/etc/config/alertmanager.yml
        - --storage.path=/data
        - --data.retention=240h # retain 10 days of data
        - --web.external-url=/
        ports:
        - containerPort: 9093
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9093
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: "/-/ready"
            port: 9093
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 15
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          # limits:
            # cpu: ?
            # memory: ?
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/config
          readOnly: true
        - name: alertmanager-storage
          mountPath: /data
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
          items:
          - key: alertmanager.yml
            path: alertmanager.yml
      - name: alertmanager-storage
        persistentVolumeClaim:
          claimName: alertmanager-storage
