---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-config
  namespace: cluster-monitoring
  labels:
    app: prometheus-server
    env: production
    monitoring: cluster
data:
  prometheus.yml: |-
    global:
      evaluation_interval: 1m
      scrape_interval: 10s
      scrape_timeout: 10s
      external_labels:
        region: aws-us-east-1
        env: production
        cluster: kubernetes-eks

    rule_files:
    - /etc/prometheus/rules/rules.yml
    - /etc/prometheus/alerts/alerts.yml

    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            - alertmanager.cluster-monitoring.svc.cluster.local:9093

    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090

    - job_name: kubernetes-apiservers
      kubernetes_sd_configs:
      - role: endpoints
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: false
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: keep
        regex: default;kubernetes;https
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        - __meta_kubernetes_endpoint_port_name

    - job_name: kubernetes-nodes
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: false
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/${1}/proxy/metrics
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__

    - job_name: kubernetes-nodes-cadvisor
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: false
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
        source_labels:
        - __meta_kubernetes_node_name
        target_label: __metrics_path__

    - job_name: kubernetes-cluster-daemonsets
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - kube-system
          - cluster-monitoring
      scheme: http
      relabel_configs:
      - action: keep
        source_labels:
        - __meta_kubernetes_pod_controller_kind
        regex: (DaemonSet)
      - action: keep
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
        regex: true
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scheme
        regex: (https?)
        target_label: __scheme__
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_path
        regex: (.+)
        target_label: __metrics_path__
      - action: replace
        source_labels:
        - __address__
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_controller_name
        target_label: kubernetes_controller_name
      # set the instance label to the name of the node
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: instance
      # set the job label to the Kubernetes namespace + controller name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_controller_name
        regex: (.+);(.+)
        replacement: $1/$2
        target_label: job
      # drop unwanted labels
      - action: labeldrop
        regex: '(controller_revision_hash|pod_template_generation)'

    - job_name: kubernetes-cluster-services
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - kube-system
          - kube-events
          - cluster-monitoring
      scheme: http
      relabel_configs:
      - action: keep
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scrape
        regex: true
      - action: replace
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scheme
        regex: (https?)
        target_label: __scheme__
      - action: replace
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_path
        regex: (.+)
        target_label: __metrics_path__
      - action: replace
        source_labels:
        - __address__
        - __meta_kubernetes_service_annotation_prometheus_io_port
        regex: ([^:]+)(?::\d+)?;(\d+)
        target_label: __address__
        replacement: $1:$2
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      # set the instance label to the name of the Pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      # set the job name to the Kubernetes namespace + service name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_service_name
        regex: (.+);(.+)
        replacement: $1/$2
        target_label: job
      # keep the Kubernetes namespace, service name, controller kind, and container name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_service_name
        target_label: kubernetes_service_name
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_controller_kind
        target_label: kubernetes_controller_kind
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container_name
      # drop unwanted labels
      - action: labeldrop
        regex: 'kubernetes_io_.+'
