---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-rules
  namespace: cluster-monitoring
  labels:
    app: prometheus-server
    monitoring: cluster
    env: production
data:
  rules.yml: |-
    groups:
      - name: elasticsearch-rules
        interval: 1m
        rules:
          - record: "elasticsearch:node:disk_used_percent"
            expr: ((elasticsearch_filesystem_data_size_bytes - elasticsearch_filesystem_data_available_bytes) / elasticsearch_filesystem_data_size_bytes) * 100
