---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-server
  namespace: cluster-monitoring
  labels:
    app: prometheus-server
    monitoring: cluster
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus-cluster-monitoring
  labels:
    app: prometheus-server
    monitoring: cluster
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus-cluster-monitoring
  labels:
    app: prometheus-server
    monitoring: cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-cluster-monitoring
subjects:
- kind: ServiceAccount
  name: prometheus-server
  namespace: cluster-monitoring
