---
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: cluster-monitoring
  labels:
    app: kube-state-metrics
    monitoring: cluster
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  clusterIP: None
  ports:
  - name: kube-state-metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kube-state-metrics
    monitoring: cluster
